### ISSUE TITLE
Mac version possible?

### ISSUE THREAD

**Issue by acrylicode** [EnviralDesign/GeoPix#56]
Hi, this project looks very promising, thank you so much!

Would it be possible to get this working on a Mac? Or is there any dependency that only runs natively in Windows? If it is possible could maybe someone guide me on how to get this working on a Mac? Maybe the python requirements.txt or all the needed dependencies.

Greetings.

**Comment by cojosass** [comment]
I second this

**Comment by cybernetchi** [comment]
yes, mac version please :)

**Comment by EnviralDesign** [comment]
Has anyone given the latest Vulcan branch of geopix a try? It in theory should sort of work now on macs, though there are still some windows things going on that will prevent it from being fully compatible.. however a big step closer. 

If anyone does get the chance to try it out please let me know how it goes and leave any specific issues you find here.

**Comment by jessesep** [comment]
How would we go about installing it on a mac?

**Comment by EnviralDesign** [comment]
You can download a zip of the repo of the Vulcan branch here:

https://github.com/EnviralDesign/GeoPix/tree/vulcan-update

Uncompress the zip file to a folder, then open the geopix.toe with the notes version of touchdesigner that is listed in the readme.

I need to update it to latest soon, but it's very close.

**Comment by akre54** [comment]
I made a bash version of the assets download script in #63 which removes the Windows req. As others have pointed out, launching on Mac is a matter of just opening the toe in TD, but right now it has a bunch of errors. Happy to help debug if there's interest.

> SOURCE: DAT : 3 : /software/top/Time/timeline_collapsed/timePreview/script2_callbacks
ERROR: (95) Traceback (most recent call last):
  File "/software/top/Time/timeline_collapsed/timePreview/script2_callbacks", line 12, in onCook
td.tdError: Module compilation error. See /software/top/PixelMapEditor/logic/local/modules/tdUtils for details.
>
>
> SOURCE: DAT : 3 : /software/top/PixelMapEditor/logic/local/modules/tdUtils
ERROR: (95) Traceback (most recent call last):
  File "/software/top/PixelMapEditor/logic/local/modules/tdUtils", line 19
    r = previousimport(*args, **kw)
ModuleNotFoundError: No module named 'natsort'
>
>
> SOURCE: DAT : 3 : /UberGui/Scheduler/chopexec_updateTime
ERROR: (110) Traceback (most recent call last):
  File "/UberGui/Scheduler/chopexec_updateTime", line 5, in whileOn
td.tdAttributeError: 'td.containerCOMP' object has no attribute 'GetCurrentTime_Epoch' Context:/UberGui/Scheduler

**Comment by user06754** [comment]
> Awesome, thank you for the detailed logs and updates! There seem to be some shaders that are taking too long, and some other Vulcan errors. I'll begin looking into this soon.

hey, really appreciate the work you've put into this. Just wondering if there are any news on those errors and getting it to run smoothly on Mac OS?

big thanks

josh

**Comment by wiwkvi** [comment]
I would also be interested in Mac version. At this point, I tried downloading from the Vulcan branch but got errors after opening the .toe file. 

thanks,

Mariam
